name = "matematikkocum"
compatibility_date = "2026-08-21"
pages_build_output_dir = "dist"

# Cloudflare Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "matematikkocum"
database_id = "b5272320-8232-4914-afea-af65a14f1d48"

# R2 binding will be added after the production bucket is created.
