import './admin.css'

const roleLabels = { admin: 'Yönetici', teacher: 'Öğretmen', student: 'Öğrenci', parent: 'Veli' }
const escapeHtml = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' })[c])
const fmtDate = value => value ? new Intl.DateTimeFormat('tr-TR', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(new Date(value.replace(' ', 'T') + (value.endsWith('Z') ? '' : 'Z'))) : '—'

const icon = name => ({ home:'⌂', users:'♙', courses:'▣', tasks:'✓', exams:'◇', messages:'◱', activity:'◌', settings:'⚙' }[name] || '•')

const renderShell = (currentUser) => `<div class="admin-app"><aside class="admin-sidebar"><div class="admin-brand"><span>✕</span><div><strong>Matematik Koçum</strong><small>Yönetim Merkezi</small></div></div><nav class="admin-nav"><button class="admin-nav-item active" data-view="overview">${icon('home')}<span>Genel Bakış</span></button><button class="admin-nav-item" data-view="users">${icon('users')}<span>Kullanıcılar</span></button><button class="admin-nav-item" data-view="courses">${icon('courses')}<span>Dersler</span></button><button class="admin-nav-item" data-view="tasks">${icon('tasks')}<span>Ödevler</span></button><button class="admin-nav-item" data-view="exams">${icon('exams')}<span>Sınavlar</span></button><button class="admin-nav-item" data-view="messages">${icon('messages')}<span>Mesajlar</span></button><button class="admin-nav-item" data-view="activity">${icon('activity')}<span>Aktiviteler</span></button></nav><div class="admin-sidebar-bottom"><button class="admin-nav-item" data-view="settings">${icon('settings')}<span>Ayarlar</span></button><div class="admin-user"><div class="admin-avatar">${escapeHtml((currentUser.fullName || 'A').slice(0,1).toUpperCase())}</div><div><strong>${escapeHtml(currentUser.fullName || currentUser.username)}</strong><small>Baş yönetici</small></div><button id="adminLogout" title="Çıkış">↗</button></div></div></aside><div class="admin-main"><header class="admin-header"><div class="mobile-brand"><span>✕</span> Matematik Koçum</div><div class="admin-header-actions"><button class="icon-button" id="refreshDashboard" title="Yenile">↻</button><button class="icon-button" title="Bildirimler">♢</button><div class="admin-header-user"><div class="admin-avatar small">${escapeHtml((currentUser.fullName || 'A').slice(0,1).toUpperCase())}</div><div><strong>${escapeHtml(currentUser.fullName || currentUser.username)}</strong><small>Yönetici</small></div></div></div></header><main id="adminContent" class="admin-content"></main></div></div>`

const statCard = (label, value, hint, cls='') => `<article class="stat-card ${cls}"><div class="stat-icon">${hint.icon}</div><div class="stat-info"><span>${label}</span><strong>${value}</strong><small>${hint.text}</small></div></article>`

const overviewView = data => `<div class="page-heading"><div><span class="page-eyebrow">YÖNETİM PANELİ</span><h1>Genel Bakış</h1><p>Platformun bugünkü durumunu tek ekrandan takip et.</p></div><button class="button button-primary" data-action="new-user">+ Yeni Kullanıcı</button></div><section class="stats-grid">${statCard('Toplam Kullanıcı', data.stats.users, {icon:'♙',text:`${data.stats.students} öğrenci · ${data.stats.teachers} öğretmen`})}${statCard('Aktif Öğrenciler', data.stats.students, {icon:'⌁',text:'Öğrenme yolculuğunda'})}${statCard('Öğretmenler', data.stats.teachers, {icon:'◇',text:`${data.stats.parents} veli bağlı`})}${statCard('Toplam Ders', data.stats.courses, {icon:'▣',text:`${data.stats.assignments} ödev oluşturuldu`})}</section><div class="admin-grid-two"><section class="panel-card"><div class="panel-heading"><div><h2>Hızlı İşlemler</h2><span>En sık kullandığın yönetim işlemleri</span></div></div><div class="quick-grid"><button data-action="new-user"><b>♙</b><strong>Kullanıcı oluştur</strong><span>Öğrenci, öğretmen veya veli ekle</span></button><button data-view="users"><b>⌕</b><strong>Kullanıcıları yönet</strong><span>Hesapları ve rollerini düzenle</span></button><button data-view="courses"><b>▣</b><strong>Dersleri görüntüle</strong><span>Aktif dersleri kontrol et</span></button><button data-view="activity"><b>◌</b><strong>Aktiviteleri incele</strong><span>Son sistem hareketlerini gör</span></button></div></section><section class="panel-card"><div class="panel-heading"><div><h2>Sistem Özeti</h2><span>Canlı veritabanı durumu</span></div><span class="status-dot"><i></i> Aktif</span></div><div class="system-list"><div><span>Öğrenci</span><b>${data.stats.students}</b></div><div><span>Öğretmen</span><b>${data.stats.teachers}</b></div><div><span>Veli</span><b>${data.stats.parents}</b></div><div><span>Yönetici</span><b>${data.stats.admins}</b></div><div><span>Mesaj</span><b>${data.stats.messages}</b></div></div></section></div><section class="panel-card"><div class="panel-heading"><div><h2>Son Aktiviteler</h2><span>Sistemdeki son işlemler</span></div><button class="text-button" data-view="activity">Tümünü gör →</button></div>${activityList(data.activity)}</section>`

const activityList = items => items?.length ? `<div class="activity-list">${items.map(item => `<div class="activity-row"><div class="activity-icon">◌</div><div><strong>${escapeHtml(item.action)}</strong><span>${escapeHtml(item.fullName || item.username || 'Sistem')}</span></div><time>${fmtDate(item.createdAt)}</time></div>`).join('')}</div>` : '<div class="empty-state"><div>◌</div><strong>Henüz aktivite yok</strong><span>Sistem hareketleri burada görünecek.</span></div>'

const userRows = users => users.length ? users.map(user => `<tr><td><div class="table-user"><div class="avatar">${escapeHtml((user.fullName || user.username || 'U').slice(0,1).toUpperCase())}</div><div><strong>${escapeHtml(user.fullName || user.full_name)}</strong><small>@${escapeHtml(user.username)}</small></div></div></td><td>${escapeHtml(user.email || '—')}</td><td><span class="role-pill role-${user.role}">${escapeHtml(roleLabels[user.role] || user.role)}</span></td><td><span class="status-pill ${user.isActive ? 'active' : 'inactive'}"><i></i>${user.isActive ? 'Aktif' : 'Pasif'}</span></td><td>${escapeHtml((user.createdAt || '').slice(0,10))}</td><td><div class="row-actions"><button data-user-edit="${user.id}" title="Düzenle">✎</button><button data-user-toggle="${user.id}" data-active="${user.isActive ? 1 : 0}" title="Durumu değiştir">◉</button><button data-user-delete="${user.id}" title="Sil">×</button></div></td></tr>`).join('') : '<tr><td colspan="6"><div class="empty-state compact"><div>♙</div><strong>Kullanıcı bulunamadı</strong><span>İlk kullanıcıyı oluşturarak başla.</span></div></td></tr>'

const usersView = users => `<div class="page-heading"><div><span class="page-eyebrow">HESAP YÖNETİMİ</span><h1>Kullanıcılar</h1><p>Tüm hesapları, rollerini ve erişim durumlarını yönet.</p></div><button class="button button-primary" data-action="new-user">+ Kullanıcı Oluştur</button></div><section class="panel-card"><div class="table-toolbar"><div class="search-box">⌕<input id="userSearch" placeholder="Kullanıcı ara…"></div><button class="button button-secondary" id="refreshUsers">↻ Yenile</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Kullanıcı</th><th>E-posta</th><th>Rol</th><th>Durum</th><th>Katılım</th><th></th></tr></thead><tbody id="userRows">${userRows(users)}</tbody></table></div></section><div id="userModal"></div>`

const simpleView = (title, eyebrow, description, iconName, count, detail) => `<div class="page-heading"><div><span class="page-eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div></div><section class="empty-feature"><div class="feature-orb">${icon(iconName)}</div><h2>${count} kayıt hazır.</h2><p>${detail}</p><div class="feature-stats"><div><b>${count}</b><span>Toplam</span></div><div><b>Aktif</b><span>Durum</span></div><div><b>D1</b><span>Veri kaynağı</span></div></div></section>`

const newUserModal = () => `<div class="modal-layer" id="createUserModal"><div class="modal-backdrop" data-close-modal></div><section class="modal-card"><button class="modal-close" data-close-modal>×</button><span class="page-eyebrow">YENİ HESAP</span><h2>Kullanıcı oluştur</h2><p>Öğretmen, öğrenci, veli veya yönetici hesabı oluştur.</p><form id="createUserForm" class="modern-form"><div class="form-grid"><label>Kullanıcı adı<input name="username" required placeholder="ornek.kullanici"></label><label>Ad soyad<input name="fullName" required placeholder="Ad Soyad"></label><label>E-posta<input name="email" type="email" placeholder="ornek@mail.com"></label><label>Rol<select name="role" required><option value="student">Öğrenci</option><option value="teacher">Öğretmen</option><option value="parent">Veli</option><option value="admin">Yönetici</option></select></label><label class="wide">Geçici şifre<input name="password" type="password" required minlength="8" placeholder="En az 8 karakter"></label></div><div class="modal-actions"><span id="createMessage"></span><button type="button" class="button button-secondary" data-close-modal>Vazgeç</button><button class="button button-primary" type="submit">Hesabı Oluştur →</button></div></form></section></div>`

export const renderAdmin = async (app, currentUser) => {
  app.innerHTML = renderShell(currentUser)
  const content = document.querySelector('#adminContent')
  let overviewData = null
  let users = []

  const loadOverview = async () => {
    const response = await fetch('/api/admin/overview'); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'Yönetim verileri alınamadı.'); overviewData = data; return data
  }
  const loadUsers = async () => { const response = await fetch('/api/admin/users'); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'Kullanıcılar alınamadı.'); users = data.users || []; return users }

  const show = async view => {
    document.querySelectorAll('.admin-nav-item[data-view]').forEach(item => item.classList.toggle('active', item.dataset.view === view))
    content.innerHTML = '<div class="loading-state"><div class="spinner"></div><span>Yükleniyor…</span></div>'
    try {
      if (view === 'overview') { const data = await loadOverview(); content.innerHTML = overviewView(data) }
      else if (view === 'users') { const list = await loadUsers(); content.innerHTML = usersView(list); bindUserSearch() }
      else if (view === 'courses') { const data = await loadOverview(); content.innerHTML = simpleView('Dersler','AKADEMİK','Platformdaki aktif derslerin genel görünümü.', 'courses', data.stats.courses, 'Ders yönetimi, öğretmen atamaları ve içerik akışı bir sonraki içerik yönetimi adımında aynı panelden yönetilecek.') }
      else if (view === 'tasks') { const data = await loadOverview(); content.innerHTML = simpleView('Ödevler','AKADEMİK','Ödev trafiğini ve teslim süreçlerini takip et.', 'tasks', data.stats.assignments, 'Ödev kayıtları D1 üzerinde hazır. Yönetim ekranı aynı tasarım diliyle bu verileri kullanıyor.') }
      else if (view === 'exams') { const data = await loadOverview(); content.innerHTML = simpleView('Sınavlar','ÖLÇME & DEĞERLENDİRME','Sınav ve sonuç altyapısını takip et.', 'exams', data.stats.exams, 'Sınav kayıtları ve öğrenci sonuçları D1 şemasında hazır.') }
      else if (view === 'messages') { const data = await loadOverview(); content.innerHTML = simpleView('Mesajlar','İLETİŞİM','Platform içi iletişim trafiğini izle.', 'messages', data.stats.messages, `${data.stats.unreadMessages} okunmamış mesaj bulunuyor.`) }
      else if (view === 'activity') { const data = await loadOverview(); content.innerHTML = `<div class="page-heading"><div><span class="page-eyebrow">SİSTEM KAYITLARI</span><h1>Aktiviteler</h1><p>Yönetim işlemlerinin güvenli denetim kaydı.</p></div></div><section class="panel-card"><div class="panel-heading"><div><h2>Son hareketler</h2><span>En yeni 8 işlem</span></div></div>${activityList(data.activity)}</section>` }
      else content.innerHTML = `<div class="page-heading"><div><span class="page-eyebrow">SİSTEM</span><h1>Ayarlar</h1><p>Platform ayarları için temel yönetim alanı.</p></div></div><section class="empty-feature"><div class="feature-orb">⚙</div><h2>Yönetim ayarları</h2><p>Güvenlik, roller ve sistem tercihleri burada yönetilecek.</p></section>`
      bindActions()
    } catch (error) { content.innerHTML = `<div class="error-state"><strong>Bir sorun oluştu.</strong><span>${escapeHtml(error.message)}</span><button class="button button-secondary" id="retryView">Tekrar dene</button></div>`; document.querySelector('#retryView')?.addEventListener('click', () => show(view)) }
  }

  const bindUserSearch = () => document.querySelector('#userSearch')?.addEventListener('input', e => { const q = e.target.value.toLowerCase().trim(); document.querySelector('#userRows').innerHTML = userRows(users.filter(u => `${u.fullName} ${u.username} ${u.email || ''}`.toLowerCase().includes(q))) ; bindUserActions() })
  const bindUserActions = () => {
    document.querySelectorAll('[data-user-toggle]').forEach(button => button.addEventListener('click', async () => { const id = button.dataset.userToggle; const active = button.dataset.active === '1'; const response = await fetch('/api/admin/users', { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({id,isActive:!active}) }); if (!response.ok) { const d=await response.json(); alert(d.error || 'İşlem başarısız.'); return } await show('users') }))
    document.querySelectorAll('[data-user-delete]').forEach(button => button.addEventListener('click', async () => { if (!confirm('Bu kullanıcıyı kalıcı olarak silmek istediğine emin misin?')) return; const response = await fetch(`/api/admin/users?id=${encodeURIComponent(button.dataset.userDelete)}`, {method:'DELETE'}); if (!response.ok) { const d=await response.json(); alert(d.error || 'Silinemedi.'); return } await show('users') }))
  }
  const bindActions = () => { document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => show(b.dataset.view))); document.querySelectorAll('[data-action="new-user"]').forEach(b => b.addEventListener('click', openNewUser)); bindUserActions(); document.querySelector('#refreshUsers')?.addEventListener('click', () => show('users')); document.querySelector('#refreshDashboard')?.addEventListener('click', () => show('overview')) }
  const openNewUser = () => { const host = document.querySelector('#userModal') || document.body.appendChild(Object.assign(document.createElement('div'), { id:'userModal' })); host.innerHTML = newUserModal(); host.querySelectorAll('[data-close-modal]').forEach(b => b.addEventListener('click', () => host.innerHTML = '')); host.querySelector('#createUserForm').addEventListener('submit', async e => { e.preventDefault(); const message = host.querySelector('#createMessage'); message.textContent='Oluşturuluyor…'; try { const response = await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))}); const data=await response.json(); if(!response.ok||!data.ok) throw new Error(data.error||'Oluşturulamadı.'); host.innerHTML=''; await show('users') } catch(error){message.textContent=error.message} }) }

  document.querySelector('#adminLogout').addEventListener('click', async () => { await fetch('/api/auth/logout',{method:'POST'}); window.location.reload() })
  await show('overview')
}
