/* Activates the people feature UI without changing the existing design. */
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const role=()=>{const t=document.querySelector('.workspace-role')?.textContent||'';return t.includes('Öğretmen')?'teacher':t.includes('Öğrenci')?'student':t.includes('Veli')?'parent':'admin'}
const api=(action,body={},method='GET')=>fetch(`/api/relationships?action=${encodeURIComponent(action)}${method==='GET'&&body.q?`&q=${encodeURIComponent(body.q)}`:''}`,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:method==='GET'?undefined:JSON.stringify(body)}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||'İşlem başarısız.');return d})
const avatar=p=>p?.avatar_data?`<span class="people-avatar" style="background-image:url('${p.avatar_data}');background-size:cover;background-position:center"></span>`:`<span class="people-avatar">${esc((p?.full_name||p?.username||'?').slice(0,1).toUpperCase())}</span>`
function addNav(){
 if(['student','parent'].includes(role())||document.querySelector('[data-page="parents"]'))return
 const sec=[...document.querySelectorAll('.nav-section')].find(x=>x.textContent.includes('Kullanıcılar'));const body=sec?.querySelector('.nav-accordion-body');if(!body)return
 const b=document.createElement('button');b.className='workspace-nav';b.dataset.page='parents';b.innerHTML='<span aria-hidden="true">◉</span><span>Veliler</span>';body.appendChild(b)
}
function modal(title,html){const h=document.querySelector('#wsModalHost');if(!h)return;h.innerHTML=`<div class="modal-layer"><div class="modal-backdrop" data-people-close></div><section class="modal-card ws-modal-card"><button class="modal-close" data-people-close aria-label="Kapat">×</button><span class="eyebrow">KULLANICILAR</span><h2>${esc(title)}</h2><div class="modal-desc">${html}</div></section></div>`;h.querySelectorAll('[data-people-close]').forEach(x=>x.onclick=()=>h.innerHTML='')}
async function renderParents(){
 const c=document.querySelector('#workspaceContent');if(!c)return
 const admin=role()==='admin';const q=admin?(c.querySelector('#peopleSearch')?.value||''):'';const d=admin?await api('tree',{q}):await api('list');
 let body='';
 if(admin){body=(d.teachers||[]).map(t=>`<section class="hub-panel open"><button class="hub-header" data-person-toggle><span class="hub-title">${avatar(t)}<strong>${esc(t.full_name)}</strong><small>Öğretmen · @${esc(t.username)}</small></span><span class="hub-chevron">⌄</span></button><div class="hub-body"><div class="hub-body-inner">${(t.students||[]).map(s=>`<section class="hub-panel open"><button class="hub-header" data-person-toggle><span class="hub-title">${avatar(s)}<strong>${esc(s.full_name)}</strong><small>Öğrenci · @${esc(s.username)}</small></span><span class="hub-chevron">⌄</span></button><div class="hub-body"><div class="hub-body-inner">${(s.parents||[]).map(p=>`<article class="data-row">${avatar(p)}<div><b>${esc(p.full_name)}</b><span>Veli · @${esc(p.username)}</span><small>${esc(p.email||'')}</small></div></article>`).join('')||'<div class="workspace-empty"><p>Bağlı veli yok.</p></div>'}</div></div></section>`).join('')||'<div class="workspace-empty"><p>Bu öğretmene bağlı öğrenci yok.</p></div>'}</div></div></section>`).join('')||'<div class="workspace-empty"><p>Sonuç bulunamadı.</p></div>'}
 else {const by=new Map((d.students||[]).map(s=>[s.id,{...s,parents:[]} ]));(d.parents||[]).forEach(p=>by.get(p.student_id)?.parents.push(p));body=[...by.values()].map(s=>`<section class="hub-panel open"><button class="hub-header" data-person-toggle><span class="hub-title">${avatar(s)}<strong>${esc(s.full_name)}</strong><small>Öğrenci · ${s.parents.length} veli</small></span><span class="hub-chevron">⌄</span></button><div class="hub-body"><div class="hub-body-inner">${s.parents.map(p=>`<article class="data-row">${avatar(p)}<div><b>${esc(p.full_name)}</b><span>Veli · @${esc(p.username)}</span></div></article>`).join('')||'<div class="workspace-empty"><p>Bağlı veli yok.</p></div>'}</div></div></section>`).join('')||'<div class="workspace-empty"><p>Henüz veli yok.</p></div>'}
 c.innerHTML=`<div class="workspace-heading"><div><span class="eyebrow">KULLANICILAR</span><h2>Veliler</h2><p>Öğrenci ve veli bağlantılarını yönetin.</p></div><button class="button button-primary" id="addParentBtn">+ Veli Ekle</button></div>${admin?`<div class="people-search"><input id="peopleSearch" placeholder="Öğretmen, öğrenci veya veli ara…" value="${esc(q)}"><button class="button button-secondary" id="peopleSearchBtn">Ara</button></div>`:''}<div class="people-tree">${body}</div>`
 c.querySelector('#peopleSearchBtn')?.addEventListener('click',renderParents)
 c.querySelector('#addParentBtn')?.addEventListener('click',async()=>{const x=await api('list');modal('Veli Ekle',`<form id="createParent" class="modern-form"><div class="form-grid"><label>Ad Soyad<input name="fullName" required></label><label>Kullanıcı adı<input name="username" required></label><label>E-posta<input name="email" type="email"></label><label>Şifre<input name="password" type="password" required></label><label>Öğrenci<select name="studentId" required>${(x.students||[]).map(s=>`<option value="${s.id}">${esc(s.full_name)} · @${esc(s.username)}</option>`).join('')}</select></label><label>Yakınlık<input name="relationship" value="Veli"></label><div class="wide modal-actions"><span id="parentMsg"></span><button class="button button-primary">Veli Oluştur</button></div></div></form>`);document.querySelector('#createParent').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));try{await api('create-parent',b,'POST');document.querySelector('#wsModalHost').innerHTML='';renderParents()}catch(err){document.querySelector('#parentMsg').textContent=err.message}}})
 c.querySelectorAll('[data-person-toggle]').forEach(b=>b.onclick=()=>{const p=b.closest('.hub-panel');p.classList.toggle('open')})
}
function boot(){const w=document.querySelector('.workspace');if(!w)return false;addNav();return true}
const observer=new MutationObserver(()=>boot());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{const b=e.target.closest('[data-page="parents"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();renderParents()},true);boot()
