import './phase4-ui.css'

const randPassword=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';let s='';for(let i=0;i<14;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
const csv=(rows)=>{if(!rows.length)return '';const keys=[...new Set(rows.flatMap(x=>Object.keys(x)))];return [keys,...rows.map(x=>keys.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`))].map(r=>r.join(',')).join('\n')}
function download(name,text,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function getRows(){const p=document.querySelector('#workspaceContent');if(!p)return [];return [...p.querySelectorAll('table tbody tr')].map(tr=>{const cells=[...tr.querySelectorAll('th,td')].map(x=>x.innerText.trim());return cells.reduce((o,v,i)=>{o['Alan '+(i+1)]=v;return o},{})}).filter(x=>Object.values(x).some(Boolean))}
function exportButton(){const p=document.querySelector('#workspaceContent');if(!p||p.querySelector('[data-phase4-export]'))return;const title=(p.querySelector('h1,h2')?.textContent||'liste').trim();if(!p.querySelector('table'))return;const b=document.createElement('button');b.type='button';b.dataset.phase4Export='1';b.className='button button-secondary phase4-export';b.textContent='Excel / CSV Dışa Aktar';b.onclick=async()=>{const rows=await getRows();download(`${title.replace(/[^a-z0-9ğüşöçıİĞÜŞÖÇ]+/gi,'-')}.csv`,csv(rows))};(p.querySelector('.workspace-heading')||p.firstElementChild)?.append(b)}
function passwordHelper(){document.querySelectorAll('form').forEach(f=>{const input=f.querySelector('input[type=password]');if(!input||f.dataset.passwordRegistration!=='1'||f.querySelector('[data-password-generate]'))return;input.type='text';const b=document.createElement('button');b.type='button';b.className='phase4-password';b.dataset.passwordGenerate='1';b.textContent='Güvenli şifre oluştur';b.onclick=()=>{input.value=randPassword();input.dispatchEvent(new Event('input',{bubbles:true}))};input.insertAdjacentElement('afterend',b)})}
function usernameGuard(){document.querySelectorAll('form').forEach(f=>{const input=f.querySelector('input[name=username],input[name=user_name]');if(!input||f.dataset.phase4User==='1')return;f.dataset.phase4User='1';let note=document.createElement('small');note.className='phase4-username-note';input.after(note);let timer;input.addEventListener('input',()=>{clearTimeout(timer);const v=input.value.trim();if(!v){note.textContent='';return}timer=setTimeout(async()=>{try{const r=await fetch('/api/users/check-username?username='+encodeURIComponent(v),{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();note.textContent=d.available===false?'Bu kullanıcı adı zaten kullanılıyor.':'Kullanıcı adı uygun.';note.dataset.taken=d.available===false?'1':'0'}catch{}},350)})})}
function boot(){const run=()=>{exportButton();passwordHelper();usernameGuard()};run();new MutationObserver(run).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()
