const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const roleNames={admin:'Baş yönetici',teacher:'Öğretmen',student:'Öğrenci',parent:'Veli'}
const icons={dashboard:'⌂',calendar:'◷',courses:'▣',assignments:'✓',exams:'◇',coaching:'♙',evaluations:'◈',progress:'⌁',videos:'▷',messages:'◱',reports:'▥',settings:'⚙'}
const labels={dashboard:'Genel Bakış',calendar:'Takvim',courses:'Dersler',assignments:'Ödevler',exams:'Sınavlar',coaching:'Koçluk',evaluations:'Değerlendirmeler',progress:'Gelişim',videos:'Video Dersler',messages:'Mesajlar',reports:'Raporlar',settings:'Ayarlar'}
const formatDate=v=>v?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):''
const empty=(title,text)=>`<div class="workspace-empty"><div class="empty-icon">✦</div><h3>${title}</h3><p>${text}</p></div>`

const navItems=(role)=>{ const base=['dashboard','calendar','courses','assignments','exams','coaching','evaluations','progress','videos','messages','reports','settings']; return base.map(k=>`<button class="workspace-nav ${k==='dashboard'?'active':''}" data-page="${k}"><span>${icons[k]}</span><b>${labels[k]}</b></button>`).join('') }

export const renderWorkspace=async(app,user,onLogout)=>{
  app.innerHTML=`<div class="workspace"><aside class="workspace-sidebar"><div class="workspace-brand"><span class="brand-mark">M</span><div><strong>Matematik Koçum</strong><small>Akıllı eğitim platformu</small></div></div><div class="workspace-role"><span class="role-dot"></span>${roleNames[user.role]||'Kullanıcı'} paneli</div><nav>${navItems(user.role)}</nav><div class="workspace-side-bottom"><button class="workspace-nav" data-page="settings"><span>⚙</span><b>Ayarlar</b></button><button class="logout-button" id="workspaceLogout"><span>↪</span> Güvenli Çıkış</button></div></aside><section class="workspace-main"><header class="workspace-header"><button class="mobile-menu" id="mobileMenu">☰</button><div class="header-title"><span class="eyebrow">${roleNames[user.role]||'PANEL'}</span><h1 id="workspaceTitle">Genel Bakış</h1></div><div class="workspace-header-actions"><button class="header-icon" id="globalTheme" title="Tema">◐</button><button class="header-icon" id="globalRefresh" title="Yenile">↻</button><div class="profile-chip"><div class="profile-avatar">${esc((user.fullName||user.username).slice(0,1).toUpperCase())}</div><div><strong>${esc(user.fullName||user.username)}</strong><small>@${esc(user.username)}</small></div></div></div></header><main id="workspaceContent" class="workspace-content"></main></section></div>`
  const content=app.querySelector('#workspaceContent'); let current='dashboard'
  const fetchData=async(resource)=>{const r=await fetch(`/api/app?resource=${encodeURIComponent(resource)}`);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Veri alınamadı.');return d}
  const post=async(resource,body,method='POST')=>{const r=await fetch(`/api/app?resource=${encodeURIComponent(resource)}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'İşlem başarısız.');return d}
  const heading=(eyebrow,title,text,action='')=>`<div class="workspace-heading"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${text}</p></div>${action}</div>`
  const card=(title,body,cls='')=>`<section class="surface-card ${cls}"><div class="surface-head"><div><h3>${title}</h3></div></div>${body}</section>`
  const stat=(label,value,meta,icon)=>`<div class="metric-card"><div class="metric-icon">${icon}</div><span>${label}</span><strong>${value}</strong><small>${meta}</small></div>`

  const dashboard=async()=>{const d=(await fetchData('dashboard')).data; const s=d.stats; content.innerHTML=heading('KONTROL MERKEZİ',`Hoş geldin, ${esc(user.fullName||user.username)}.`,`Bugünkü eğitim yolculuğunun tamamı burada.`)+`<div class="metric-grid">${stat('Dersler',s.courses,'Aktif içerikler','▣')}${stat('Ödevler',s.assignments,user.role==='student'?'Bekleyen çalışmalar':'Toplam kayıt','✓')}${stat('Sınavlar',s.exams,'Yaklaşan ve sonuçlar','◇')}${stat('Mesajlar',s.messages,`${s.unreadMessages||0} okunmamış`,'◱')}</div><div class="workspace-grid wide-left">${card('Bugünkü plan',d.events?.length?`<div class="timeline">${d.events.slice(0,5).map(e=>`<div class="timeline-row"><span>${new Date(e.start_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</span><div><b>${esc(e.title)}</b><small>${esc(e.description||e.type||'Plan')}</small></div></div>`).join('')}</div>`:empty('Bugün için plan yok','Takvimden yeni bir çalışma veya ders planlayabilirsin.' )}${card('Hızlı erişim',`<div class="quick-actions"><button data-page="calendar"><span>◷</span><b>Takvimi aç</b><small>Gününü planla</small></button><button data-page="assignments"><span>✓</span><b>Ödevlere git</b><small>Çalışmalarını takip et</small></button><button data-page="progress"><span>⌁</span><b>Gelişimini gör</b><small>Performansını incele</small></button><button data-page="messages"><span>◱</span><b>Mesajlar</b><small>İletişime geç</small></button></div>`)} </div><div class="workspace-grid">${card('Gelişim özeti',d.progress?.length?`<div class="progress-list">${d.progress.slice(0,5).map(p=>`<div><div><b>${esc(p.metric)}</b><span>${p.value}${p.target?` / ${p.target}`:''}</span></div><div class="progress-track"><i style="width:${Math.min(100,p.target?Number(p.value)/Number(p.target)*100:Math.min(100,Number(p.value)))}%"></i></div></div>`).join('')}</div>`:empty('Henüz gelişim verisi yok','İlerleme kayıtları oluşturulduğunda burada görünür.')}${card('Duyurular',`<div id="announcementMini" class="announcement-list"><span class="loading-line"></span><span class="loading-line short"></span></div>`)}</div>`; loadAnnouncementsMini() }
  const loadAnnouncementsMini=async()=>{try{const d=await fetchData('announcements');const el=app.querySelector('#announcementMini');el.innerHTML=d.items?.length?d.items.slice(0,3).map(a=>`<article><b>${esc(a.title)}</b><small>${esc(a.body).slice(0,100)}</small><time>${formatDate(a.created_at)}</time></article>`).join(''):empty('Henüz duyuru yok','Yeni duyurular burada yayınlanacak.')}catch{}}

  const calendar=async()=>{const d=await fetchData('calendar'); content.innerHTML=heading('PLANLAMA','Takvim','Ders, çalışma, sınav ve kişisel hedeflerini tek yerde yönet.',`<button class="button button-primary" data-modal="calendar">+ Plan Ekle</button>`)+card('Programın',d.items?.length?`<div class="event-list">${d.items.map(e=>`<article><div class="event-date"><b>${new Date(e.start_at).getDate()}</b><span>${new Date(e.start_at).toLocaleDateString('tr-TR',{month:'short'})}</span></div><div><b>${esc(e.title)}</b><p>${esc(e.description||'')}</p><small>${formatDate(e.start_at)} · ${esc(e.type||'Çalışma')}</small></div></article>`).join('')}</div>`:empty('Takvimin boş','İlk planını ekleyerek gününü düzenlemeye başla.')) }

  const courses=async()=>{const d=await fetchData('courses');content.innerHTML=heading('AKADEMİK','Dersler','Derslerini, içeriklerini ve öğretmen bağlantılarını yönet.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="course">+ Ders Oluştur</button>`:''))+`<div class="course-grid">${d.items?.length?d.items.map(c=>`<article class="course-card"><div class="course-art">${esc((c.subject||'D').slice(0,1))}</div><span>${esc(c.subject||'Ders')}</span><h3>${esc(c.title)}</h3><p>${esc(c.description||'Ders açıklaması eklenmemiş.')}</p><small>${esc(c.teacher_name||'Atanmış öğretmen')}</small><button class="text-link">Dersi aç →</button></article>`).join(''):empty('Henüz ders yok','Yönetici veya öğretmenin ders oluşturduğunda burada görünecek.')}</div>`}

  const assignments=async()=>{const d=await fetchData('assignments');content.innerHTML=heading('AKADEMİK','Ödevler','Teslim tarihlerini, durumları ve çalışmalarını takip et.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="assignment">+ Ödev Oluştur</button>`:''))+card('Ödev akışı',d.items?.length?`<div class="assignment-list">${d.items.map(a=>`<article><div class="assignment-icon">✓</div><div class="assignment-main"><b>${esc(a.title)}</b><span>${esc(a.course_title||'Genel çalışma')}</span><small>${a.due_at?`Teslim: ${formatDate(a.due_at)}`:'Teslim tarihi belirtilmemiş'}</small></div><span class="status-badge ${a.status||'active'}">${a.status==='submitted'?'Gönderildi':a.status==='completed'?'Tamamlandı':a.status==='late'?'Gecikti':'Bekliyor'}</span>${user.role==='student'&&a.status==='pending'?`<button class="button button-small" data-submit-assignment="${a.id}">Teslim et</button>`:''}</article>`).join('')}</div>`:empty('Ödev bulunmuyor','Yeni bir ödev atandığında burada görünecek.'))}

  const exams=async()=>{const d=await fetchData('exams');content.innerHTML=heading('ÖLÇME','Sınavlar','Sınav takvimini ve sonuçlarını tek ekranda incele.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="exam">+ Sınav Oluştur</button>`:''))+card('Sınavlar',d.items?.length?`<div class="exam-list">${d.items.map(e=>`<article><div class="exam-icon">◇</div><div><b>${esc(e.title)}</b><span>${esc(e.subject||'Genel')} · ${e.duration_minutes||'—'} dk</span><small>${e.starts_at?formatDate(e.starts_at):'Tarih planlanmadı'}</small></div>${e.score!=null?`<strong class="score">${e.score}</strong>`:'<span class="status-badge active">Planlandı</span>'}</article>`).join('')}</div>`:empty('Sınav yok','Sınavlar oluşturulduğunda burada listelenecek.'))}

  const coaching=async()=>{const d=await fetchData('coaching');content.innerHTML=heading('KOÇLUK','Koçluk','Hedeflerini, takip planını ve görüşme notlarını yönet.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="coaching">+ Hedef Ekle</button>`:''))+card('Aktif planlar',d.items?.length?`<div class="goal-list">${d.items.map(p=>`<article><div class="goal-icon">♙</div><div><b>${esc(p.goal)}</b><span>${esc(p.student_name||'Öğrenci')} · ${esc(p.coach_name||'Koç')}</span><small>${esc(p.notes||'Takip notu bulunmuyor.')}</small></div><span class="status-badge ${p.status}">${p.status==='active'?'Aktif':p.status}</span></article>`).join('')}</div>`:empty('Koçluk planı yok','Hedefler oluşturulduğunda burada takip edebilirsin.'))}

  const evaluations=async()=>{const d=await fetchData('evaluations');content.innerHTML=heading('DEĞERLENDİRME','Değerlendirmeler','Geri bildirimleri, puanları ve akademik değerlendirmeleri takip et.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="evaluation">+ Değerlendirme</button>`:''))+card('Değerlendirme geçmişi',d.items?.length?`<div class="evaluation-list">${d.items.map(e=>`<article><div><b>${esc(e.title)}</b><span>${esc(e.student_name||'Öğrenci')} · ${formatDate(e.created_at)}</span><p>${esc(e.feedback||'Geri bildirim yok.')}</p></div><strong>${Number(e.score||0)}<small>/100</small></strong></article>`).join('')}</div>`:empty('Değerlendirme yok','İlk değerlendirme oluşturulduğunda burada görünür.'))}

  const progress=async()=>{const d=await fetchData('progress');const grouped={};(d.items||[]).forEach(p=>(grouped[p.metric]??=[]).push(p));content.innerHTML=heading('GELİŞİM','Gelişim Merkezi','Performansını ölç, hedeflerinle karşılaştır ve istikrarlı ilerle.',user.role!=='parent'?`<button class="button button-primary" data-modal="progress">+ İlerleme Ekle</button>`:'')+`<div class="progress-dashboard">${Object.keys(grouped).length?Object.entries(grouped).map(([metric,arr])=>{const p=arr[0];const pct=p.target?Math.min(100,p.value/p.target*100):Math.min(100,p.value);return `<article class="progress-card"><span>${esc(metric)}</span><strong>${p.value}</strong><small>${p.target?`Hedef ${p.target}`:'Kayıt'}</small><div class="progress-track large"><i style="width:${pct}%"></i></div><em>${p.period||'Güncel dönem'}</em></article>`}).join(''):empty('Henüz veri yok','İlerleme kayıtları eklendiğinde performansın burada görünecek.')}</div>`}

  const videos=async()=>{const d=await fetchData('videos');content.innerHTML=heading('ÖĞRENME','Video Dersler','Konu anlatımlarını ve tekrar videolarını tek kütüphanede bul.',(['admin','teacher'].includes(user.role)?`<button class="button button-primary" data-modal="video">+ Video Ekle</button>`:''))+`<div class="video-grid">${d.items?.length?d.items.map(v=>`<article class="video-card"><div class="video-cover"><span>▷</span><small>${esc(v.subject||'Ders')}</small></div><div><h3>${esc(v.title)}</h3><p>${esc(v.description||'')}</p><small>${esc(v.teacher_name||'Matematik Koçum')}</small></div></article>`).join(''):empty('Video kütüphanesi boş','İlk video ders eklendiğinde burada görünecek.')}</div>`}

  const messages=async()=>{const d=await fetchData('messages');content.innerHTML=heading('İLETİŞİM','Mesajlar','Öğretmen, öğrenci, veli ve yöneticilerle güvenli iletişim kur.',`<button class="button button-primary" data-modal="message">+ Yeni Mesaj</button>`)+card('Mesaj kutusu',d.items?.length?`<div class="message-list">${d.items.map(m=>`<article class="${!m.read_at&&m.receiver_id===user.id?'unread':''}"><div class="message-avatar">${esc((m.sender_name||'?').slice(0,1))}</div><div><b>${esc(m.sender_id===user.id?'Sen → '+(m.receiver_name||'Kullanıcı'):(m.sender_name||'Kullanıcı'))}</b><p>${esc(m.body)}</p><small>${formatDate(m.created_at)}</small></div>${!m.read_at&&m.receiver_id===user.id?`<button class="text-button" data-read-message="${m.id}">Okundu</button>`:''}</article>`).join('')}</div>`:empty('Mesaj kutun boş','Yeni bir mesaj aldığında burada göreceksin.'))}

  const reports=async()=>{const d=(await fetchData('dashboard')).data;content.innerHTML=heading('ANALİZ','Raporlar','Platform verilerini sade, anlaşılır ve karar vermeyi kolaylaştıran özetlerle incele.')+`<div class="report-grid">${stat('Toplam ders',d.stats.courses,'Kayıtlı ders','▣')}${stat('Ödev',d.stats.assignments,'Takip edilen','✓')}${stat('Sınav',d.stats.exams,'Ölçme kaydı','◇')}${stat('Mesaj',d.stats.messages,'İletişim','◱')}</div>`+card('Performans özeti',d.progress?.length?`<div class="report-bars">${d.progress.slice(0,8).map(p=>`<div><span>${esc(p.metric)}</span><b>${p.value}</b><div class="progress-track"><i style="width:${Math.min(100,p.target?p.value/p.target*100:p.value)}%"></i></div></div>`).join('')}</div>`:empty('Rapor verisi oluşmadı','Ders, sınav ve gelişim kayıtları geldikçe analizler otomatik oluşur.'))}

  const settings=async()=>{const d=await fetchData('settings');content.innerHTML=heading('SİSTEM','Ayarlar','Hesap ve görünüm tercihlerini yönet.')+card('Görünüm',`<form id="settingsForm" class="settings-form"><label>Tema<select name="theme"><option value="dark" ${d.settings.theme==='dark'?'selected':''}>Koyu</option><option value="light" ${d.settings.theme==='light'?'selected':''}>Açık</option><option value="system" ${d.settings.theme==='system'?'selected':''}>Sistem</option></select></label><label class="switch-row"><span><b>Bildirimler</b><small>Yeni mesaj ve görev bildirimlerini göster.</small></span><input type="checkbox" name="notifications" ${d.settings.notifications?'checked':''}></label><label>Dil<select name="language"><option value="tr" selected>Türkçe</option></select></label><button class="button button-primary">Değişiklikleri kaydet</button><span id="settingsNote"></span></form>`)}

  const pages={dashboard,calendar,courses,assignments,exams,coaching,evaluations,progress,videos,messages,reports,settings}
  const show=async(page)=>{current=page;app.querySelectorAll('.workspace-nav[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.querySelector('#workspaceTitle').textContent=labels[page]||'Panel';content.innerHTML='<div class="workspace-loading"><span></span><span></span><span></span></div>';try{await pages[page]()}catch(e){content.innerHTML=`<div class="error-state"><b>Bir sorun oluştu.</b><span>${esc(e.message)}</span><button class="button button-secondary" data-retry>Tekrar dene</button></div>`}}

  const modal=type=>{const configs={calendar:['Yeni plan','calendar',[['title','Başlık','text'],['startAt','Başlangıç','datetime-local'],['endAt','Bitiş','datetime-local'],['type','Tür','text'],['description','Not','text']]],course:['Yeni ders','course',[['title','Ders adı','text'],['subject','Ders / alan','text'],['description','Açıklama','text']]],assignment:['Yeni ödev','assignment',[['title','Ödev başlığı','text'],['dueAt','Teslim tarihi','datetime-local'],['description','Açıklama','text']]],exam:['Yeni sınav','exam',[['title','Sınav adı','text'],['subject','Ders / alan','text'],['startsAt','Başlangıç','datetime-local'],['durationMinutes','Süre (dk)','number']]],coaching:['Yeni koçluk hedefi','coaching',[['studentId','Öğrenci ID','text'],['goal','Hedef','text'],['nextReviewAt','Sonraki görüşme','date'],['notes','Not','text']]],evaluation:['Yeni değerlendirme','evaluation',[['studentId','Öğrenci ID','text'],['title','Başlık','text'],['score','Puan','number'],['feedback','Geri bildirim','text']]],progress:['Yeni gelişim kaydı','progress',[['metric','Metrik','text'],['value','Değer','number'],['target','Hedef','number'],['period','Dönem','text']]],video:['Yeni video','video',[['title','Video başlığı','text'],['url','Video URL','url'],['subject','Ders / alan','text'],['description','Açıklama','text']]],message:['Yeni mesaj','message',[['receiverId','Alıcı kullanıcı ID','text'],['body','Mesaj','text']]]};const c=configs[type];if(!c)return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-layer" id="workspaceModal"><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><button class="modal-close" data-modal-close>×</button><span class="eyebrow">İŞLEM</span><h2>${c[0]}</h2><form id="workspaceModalForm" class="modern-form">${c[2].map(x=>`<label>${x[1]}<input name="${x[0]}" type="${x[2]}" ${x[0]==='title'||x[0]==='goal'||x[0]==='body'?'required':''}></label>`).join('')}<div class="modal-actions"><span id="modalNote"></span><button type="button" class="button button-secondary" data-modal-close>Vazgeç</button><button class="button button-primary">Kaydet →</button></div></form></section></div>`);const layer=document.querySelector('#workspaceModal');layer.querySelectorAll('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>layer.remove()));layer.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());try{await post(type==='message'?'messages':type==='video'?'videos':type==='evaluation'?'evaluations':type==='progress'?'progress':type==='coaching'?'coaching':type==='calendar'?'calendar':type==='course'?'courses':type==='assignment'?'assignments':'exams',data);layer.remove();await show(current)}catch(err){layer.querySelector('#modalNote').textContent=err.message}})}

  app.addEventListener('click',async e=>{const nav=e.target.closest('[data-page]');if(nav){await show(nav.dataset.page);return}const modalBtn=e.target.closest('[data-modal]');if(modalBtn){modal(modalBtn.dataset.modal);return}if(e.target.closest('[data-retry]')){show(current);return}const submit=e.target.closest('[data-submit-assignment]');if(submit){try{await post('assignments',{id:submit.dataset.submitAssignment,status:'submitted'},'PATCH');await show(current)}catch(err){alert(err.message)}return}const read=e.target.closest('[data-read-message]');if(read){await post('messages',{id:read.dataset.readMessage},'PATCH');await show(current)}})
  app.querySelector('#workspaceLogout').addEventListener('click',async()=>{await onLogout();location.reload()})
  app.querySelector('#globalRefresh').addEventListener('click',()=>show(current))
  app.querySelector('#globalTheme').addEventListener('click',()=>{document.documentElement.classList.toggle('light');localStorage.setItem('mk_theme',document.documentElement.classList.contains('light')?'light':'dark')})
  app.querySelector('#mobileMenu').addEventListener('click',()=>app.querySelector('.workspace-sidebar').classList.toggle('open'))
  show('dashboard')
}
