const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const roles={admin:'Baş Yönetici',teacher:'Öğretmen',student:'Öğrenci',parent:'Veli'}
const labels={dashboard:'Genel Bakış',calendar:'Takvim',courses:'Dersler',assignments:'Ödevler',exams:'Sınavlar',coaching:'Koçluk',evaluations:'Değerlendirmeler',progress:'Gelişim',videos:'Video Dersler',messages:'Mesajlar',reports:'Raporlar',settings:'Ayarlar'}
const icons={dashboard:'⌂',calendar:'◷',courses:'▣',assignments:'✓',exams:'◇',coaching:'♙',evaluations:'◈',progress:'⌁',videos:'▷',messages:'◱',reports:'▥',settings:'⚙'}

const nav=()=>Object.keys(labels).map(k=>`<button class="workspace-nav ${k==='dashboard'?'active':''}" data-page="${k}"><span>${icons[k]}</span><b>${labels[k]}</b></button>`).join('')
const empty=(title,text)=>`<div class="workspace-empty"><div class="empty-icon">✦</div><h3>${title}</h3><p>${text}</p></div>`
const date=v=>v?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):''

export const renderWorkspace=async(app,user,onLogout)=>{
  app.innerHTML=`<div class="workspace"><aside class="workspace-sidebar"><div class="workspace-brand"><span class="brand-mark">M</span><div><strong>Matematik Koçum</strong><small>Akıllı eğitim platformu</small></div></div><div class="workspace-role"><span class="role-dot"></span>${roles[user.role]||'Kullanıcı'} paneli</div><nav>${nav()}</nav><div class="workspace-side-bottom"><button class="workspace-nav" data-page="settings"><span>⚙</span><b>Ayarlar</b></button><button class="logout-button" id="workspaceLogout"><span>↪</span> Güvenli Çıkış</button></div></aside><section class="workspace-main"><header class="workspace-header"><button class="mobile-menu" id="mobileMenu">☰</button><div class="header-title"><span class="eyebrow">${roles[user.role]||'PANEL'}</span><h1 id="workspaceTitle">Genel Bakış</h1></div><div class="workspace-header-actions"><button class="header-icon" id="globalTheme">◐</button><button class="header-icon" id="globalRefresh">↻</button><div class="profile-chip"><div class="profile-avatar">${esc((user.fullName||user.username).slice(0,1).toUpperCase())}</div><div><strong>${esc(user.fullName||user.username)}</strong><small>@${esc(user.username)}</small></div></div></div></header><main id="workspaceContent" class="workspace-content"></main></section></div>`

  const content=app.querySelector('#workspaceContent')
  let current='dashboard'
  const get=async(resource)=>{const r=await fetch(`/api/app?resource=${encodeURIComponent(resource)}`);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Veri alınamadı.');return d}
  const post=async(resource,body,method='POST')=>{const r=await fetch(`/api/app?resource=${encodeURIComponent(resource)}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'İşlem başarısız.');return d}
  const heading=(eyebrow,title,text,action='')=>`<div class="workspace-heading"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${text}</p></div>${action}</div>`
  const card=(title,body)=>`<section class="surface-card"><div class="surface-head"><h3>${title}</h3></div>${body}</section>`
  const stat=(label,value,meta,icon)=>`<div class="metric-card"><div class="metric-icon">${icon}</div><span>${label}</span><strong>${value??0}</strong><small>${meta}</small></div>`

  const dashboard=async()=>{const d=(await get('dashboard')).data||{};const s=d.stats||{};content.innerHTML=heading('KONTROL MERKEZİ',`Hoş geldin, ${esc(user.fullName||user.username)}.`,`Bugünkü eğitim yolculuğunun tamamı burada.`)+`<div class="metric-grid">${stat('Dersler',s.courses,'Aktif içerikler','▣')}${stat('Ödevler',s.assignments,'Takip edilen','✓')}${stat('Sınavlar',s.exams,'Ölçme kayıtları','◇')}${stat('Mesajlar',s.messages,`${s.unreadMessages||0} okunmamış`,'◱')}</div><div class="workspace-grid wide-left">${card('Bugünkü plan',d.events?.length?`<div class="timeline">${d.events.slice(0,6).map(e=>`<div class="timeline-row"><span>${new Date(e.start_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</span><div><b>${esc(e.title)}</b><small>${esc(e.description||e.type||'Plan')}</small></div></div>`).join('')}</div>`:empty('Bugün için plan yok','Takvimden yeni bir çalışma veya ders planlayabilirsin.'))}${card('Hızlı erişim',`<div class="quick-actions"><button data-page="calendar"><span>◷</span><b>Takvim</b><small>Gününü planla</small></button><button data-page="assignments"><span>✓</span><b>Ödevler</b><small>Çalışmalarını takip et</small></button><button data-page="progress"><span>⌁</span><b>Gelişim</b><small>Performansını incele</small></button><button data-page="messages"><span>◱</span><b>Mesajlar</b><small>İletişime geç</small></button></div>`)}</div>`}

  const listPage=async(resource,eyebrow,title,text,createLabel='')=>{const d=await get(resource);const items=d.items||[];const action=createLabel?`<button class="button button-primary" data-simple-create="${resource}">+ ${createLabel}</button>`:'';const rows=items.length?items.map(x=>`<article class="data-row"><div><b>${esc(x.title||x.name||x.subject||x.goal||'Kayıt')}</b><span>${esc(x.description||x.body||x.feedback||x.full_name||x.student_name||x.subject||'')}</span><small>${date(x.created_at||x.due_at||x.starts_at||x.start_at||x.next_review_at)}</small></div><span class="status-badge active">${esc(x.status||'Aktif')}</span></article>`).join(''):empty('Henüz kayıt yok','Bu bölümde kayıt oluştuğunda burada görünecek.');content.innerHTML=heading(eyebrow,title,text,action)+card(title,`<div class="data-list">${rows}</div>`)}

  const pages={
    dashboard,
    calendar:()=>listPage('calendar','PLANLAMA','Takvim','Ders, çalışma, sınav ve hedeflerini tek yerde yönet.','Plan Ekle'),
    courses:()=>listPage('courses','AKADEMİK','Dersler','Derslerini ve içeriklerini yönet.',['admin','teacher'].includes(user.role)?'Ders Oluştur':''),
    assignments:()=>listPage('assignments','AKADEMİK','Ödevler','Teslim tarihlerini ve çalışmalarını takip et.', ['admin','teacher'].includes(user.role)?'Ödev Oluştur':''),
    exams:()=>listPage('exams','ÖLÇME','Sınavlar','Sınav takvimini ve sonuçlarını incele.', ['admin','teacher'].includes(user.role)?'Sınav Oluştur':''),
    coaching:()=>listPage('coaching','KOÇLUK','Koçluk','Hedeflerini ve takip planlarını yönet.', ['admin','teacher'].includes(user.role)?'Hedef Ekle':''),
    evaluations:()=>listPage('evaluations','DEĞERLENDİRME','Değerlendirmeler','Geri bildirimleri ve akademik değerlendirmeleri takip et.', ['admin','teacher'].includes(user.role)?'Değerlendirme':''),
    progress:()=>listPage('progress','GELİŞİM','Gelişim Merkezi','Performansını ölç ve hedeflerinle karşılaştır.','İlerleme Ekle'),
    videos:()=>listPage('videos','ÖĞRENME','Video Dersler','Konu anlatımlarını ve tekrar videolarını tek kütüphanede bul.', ['admin','teacher'].includes(user.role)?'Video Ekle':''),
    messages:()=>listPage('messages','İLETİŞİM','Mesajlar','Güvenli iletişim merkezinden mesajlarını yönet.','Yeni Mesaj'),
    reports:async()=>{const d=(await get('dashboard')).data||{};const s=d.stats||{};content.innerHTML=heading('ANALİZ','Raporlar','Platform verilerini sade ve anlaşılır özetlerle ince.')+`<div class="metric-grid">${stat('Toplam ders',s.courses,'Kayıtlı ders','▣')}${stat('Ödev',s.assignments,'Takip edilen','✓')}${stat('Sınav',s.exams,'Ölçme kaydı','◇')}${stat('Mesaj',s.messages,'İletişim','◱')}</div>`+card('Gelişim özeti',d.progress?.length?`<div class="progress-list">${d.progress.slice(0,8).map(p=>`<div><div><b>${esc(p.metric)}</b><span>${p.value}${p.target?` / ${p.target}`:''}</span></div><div class="progress-track"><i style="width:${Math.min(100,p.target?Number(p.value)/Number(p.target)*100:Number(p.value))}%"></i></div></div>`).join('')}</div>`:empty('Henüz gelişim verisi yok','Veriler oluştukça raporların burada görünecek.'))},
    settings:async()=>{let d={settings:{theme:'dark',notifications:true}};try{d=await get('settings')}catch{}content.innerHTML=heading('SİSTEM','Ayarlar','Hesap ve görünüm tercihlerini yönet.')+card('Görünüm',`<form id="settingsForm" class="settings-form"><label>Tema<select name="theme"><option value="dark" ${d.settings?.theme==='dark'?'selected':''}>Koyu</option><option value="light" ${d.settings?.theme==='light'?'selected':''}>Açık</option><option value="system" ${d.settings?.theme==='system'?'selected':''}>Sistem</option></select></label><label class="switch-row"><span><b>Bildirimler</b><small>Yeni mesaj ve görev bildirimlerini göster.</small></span><input type="checkbox" name="notifications" ${d.settings?.notifications!==false?'checked':''}></label><button class="button button-primary">Değişiklikleri kaydet</button><span id="settingsNote"></span></form>`);app.querySelector('#settingsForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await post('settings',{theme:f.get('theme'),notifications:f.has('notifications')});e.currentTarget.querySelector('#settingsNote').textContent='Kaydedildi.'}catch(err){e.currentTarget.querySelector('#settingsNote').textContent=err.message}})}
  }

  const show=async(page)=>{current=page;app.querySelectorAll('.workspace-nav[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.querySelector('#workspaceTitle').textContent=labels[page]||'Panel';content.innerHTML='<div class="workspace-loading"><span></span><span></span><span></span></div>';try{await pages[page]()}catch(e){content.innerHTML=`<div class="error-state"><b>Bir sorun oluştu.</b><span>${esc(e.message)}</span><button class="button button-secondary" data-retry>Tekrar dene</button></div>`}}

  app.addEventListener('click',async e=>{const navButton=e.target.closest('[data-page]');if(navButton){await show(navButton.dataset.page);return}if(e.target.closest('[data-retry]')){await show(current);return}const create=e.target.closest('[data-simple-create]');if(create){alert('Bu bölümün oluşturma formu sonraki düzenleme aşamasında açılacak.')}})
  app.querySelector('#workspaceLogout').addEventListener('click',async()=>{await onLogout();location.reload()})
  app.querySelector('#globalRefresh').addEventListener('click',()=>show(current))
  app.querySelector('#globalTheme').addEventListener('click',()=>{document.documentElement.classList.toggle('light');localStorage.setItem('mk_theme',document.documentElement.classList.contains('light')?'light':'dark')})
  app.querySelector('#mobileMenu').addEventListener('click',()=>app.querySelector('.workspace-sidebar').classList.toggle('open'))
  show('dashboard')
}
